INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"
        font_family: Noto Sans SC

site_description: '一些世界各地的摇摆舞活动相关信息收录。'
nav:
  - 首页:
    - 时间线: index.md
    - 标签: tags.md
    - 存档:
      - '2025': 2025.md
      - '2024': 2024.md
  - 地区:
    - 所有: regions.md
    - 美洲:
      - 加拿大:
        - 时间线: ca/index.md
        - 按城市划分: ca/by_city.md
        - 主办城市: ca/host_cities.md
        - 已收录活动:
          - ca/victoria-lindy-exchange-2025.md
          - ca/capital-city-stomp-2024.md
          - ca/cats-corner-exchange-2024.md
          - ca/vancouver-balboa-mini-fest-2024.md
          - ca/lindy-harvest-2024.md
          - ca/rhythm-city-mess-around-2024.md
          - ca/stardust-festival-2024.md
        - 存档:
          - ca/2025.md
          - ca/2024.md
      - 智利:
        - 时间线: cl/index.md
        - 按城市划分: cl/by_city.md
        - 主办城市: cl/host_cities.md
        - 已收录活动:
          - cl/lindy-poh-2024.md
        - 存档:
          - cl/2024.md
      - 墨西哥:
        - 时间线: mx/index.md
        - 按城市划分: mx/by_city.md
        - 主办城市: mx/host_cities.md
        - 已收录活动:
          - mx/guadalajara-lindy-exchange-2024.md
          - mx/lindy-n-balboa-maya-fest-2024.md
          - mx/mexico-lindy-querido-2024.md
        - 存档:
          - mx/2024.md
      - 美国:
        - 时间线: us/index.md
        - 按城市划分: us/by_city.md
        - 主办城市: us/host_cities.md
        - 已收录活动:
          - us/san-diego-balboa-and-lindy-exchange-2025.md
          - us/back-home-again-2025.md
          - us/lindyfest-2025.md
          - us/hot-rhythm-holiday-2025.md
          - us/california-balboa-classic-2025.md
          - us/stormy-weather-jazz-festival-2024.md
          - us/hot-jazz-jamboree-2024.md
          - us/stompology-2024.md
          - us/stardust-slow-balboa-weekend-2024.md
          - us/austin-lindy-exchange-2024.md
          - us/breaking-bal-swing-n-blues-weekend-2024.md
          - us/emerald-city-blues-festival-2024.md
          - us/bubble-city-bash-2024.md
          - us/the-american-lindy-hop-championships-2024.md
          - us/whistle-stop-2024.md
          - us/blues-muse-2024.md
          - us/stl-getdown-2024.md
          - us/great-lakes-balboa-escape-2024.md
          - us/express-track-blues-2024.md
          - us/blues-fusion-dfw-2024.md
          - us/new-york-lindy-exchange-2024.md
          - us/lindy-on-the-rocks-2024.md
          - us/hot-night-fusion-weekend-2024.md
          - us/rhythm-shuffle-2024.md
          - us/cowtown-jamborama-2024.md
          - us/camp-hollywood-2024.md
          - us/the-uptown-swingout-2024.md
          - us/swing-out-new-hampshire-2024.md
          - us/summer-swing-fest-2024.md
          - us/rittenhopalooza-2024.md
          - us/cincy-hop-2024.md
          - us/flying-home-2024.md
          - us/bal-week-2024.md
          - us/california-balboa-classic-2024.md
        - 存档:
          - us/2025.md
          - us/2024.md
    - 亚洲:
      - 亚美尼亚:
        - 时间线: am/index.md
        - 按城市划分: am/by_city.md
        - 主办城市: am/host_cities.md
        - 已收录活动:
          - am/swing-road-armenia-2024.md
        - 存档:
          - am/2024.md
      - 中国:
        - 时间线: cn/index.md
        - 按城市划分: cn/by_city.md
        - 主办城市: cn/host_cities.md
        - 已收录活动:
          - cn/nanjing-lindy-festival-2025.md
          - cn/all-balboa-exchange-2025.md
          - cn/groove-the-bluesy-bay-2025.md
          - cn/foshan-x-korea-exchange-2024.md
          - cn/shanghai-lindy-festival-2024.md
          - cn/hangzhou-blues-workshop-eddy-2024.md
          - cn/swingtime-ball-2024.md
          - cn/balboa-with-shawn-oct-2024.md
          - cn/special-training-with-juan-oct-2024.md
          - cn/workshop-with-juan-villafane-oct-2024.md
          - cn/swing-to-the-stars-2024.md
          - cn/hop-the-bay-2024.md
          - cn/juan-special-workshop-2024.md
          - cn/shanghai-balboa-weekend-2024.md
          - cn/golden-bal-week-2024.md
          - cn/swing-paramount-2024.md
          - cn/womens-jazzination-2024.md
          - cn/claudia-n-coline-workshop-2024.md
          - cn/beijing-blues-bush-2024.md
          - cn/westlake-swing-carnival-2024.md
          - cn/vans-n-nan-balboa-workshop-aug-2024.md
          - cn/blues-heat-2024.md
          - cn/solo-jazz-workshop-black-bottom-2024.md
          - cn/blues-in-green-2024.md
          - cn/swing-feast-2024.md
          - cn/balboa-greater-bay-workshop-2024.md
          - cn/hangzhou-swing-10th-anniversary-2024.md
          - cn/blues-workshop-with-taehyeon-2024.md
          - cn/jazz-do-it-2024.md
          - cn/funs-swing-exchange-2024.md
          - cn/bal-in-beijing-2024.md
          - cn/balboa-festival-2024.md
          - cn/jump-for-joy-2024.md
          - cn/dragon-boat-swing-camp-2024.md
          - cn/dali-lalla-n-sunny-workshop-2024.md
          - cn/vasu-n-nan-balboa-workshop-2024.md
          - cn/nanjing-lindy-festival-2024.md
          - cn/xiamen-kiki-house-african-dance-workshop-2024.md
          - cn/awozi-n-lis-fuzhou-workshop-2024.md
          - cn/shanghai-blues-camp-2024.md
          - cn/beijing-balboa-fever-2024.md
          - cn/jumping-swing-2024.md
          - cn/balboa-spring-camp-2024.md
          - cn/bouncy-chengdu-2024.md
          - cn/beijing-sharon-davis-workshop-2024.md
          - cn/lindy-hotpot-2024.md
          - cn/xiamen-awozi-n-lis-workshop-2024.md
          - cn/groove-the-blusy-bay-2024.md
          - cn/all-balboa-exchange-2024.md
          - cn/xiamen-jiaming-n-wanyuan-workshop-2024.md
          - cn/beijing-balboa-travel-2024.md
        - 存档:
          - cn/2025.md
          - cn/2024.md
      - 香港:
        - 时间线: hk/index.md
        - 按城市划分: hk/by_city.md
        - 主办城市: hk/host_cities.md
        - 已收录活动:
          - hk/harbourside-swing-fest-2025.md
          - hk/vasu-n-xinru-balboa-weekend-2024.md
          - hk/harbourside-swing-fest-2024.md
        - 存档:
          - hk/2025.md
          - hk/2024.md
      - 印尼:
        - 时间线: id/index.md
        - 按城市划分: id/by_city.md
        - 主办城市: id/host_cities.md
        - 已收录活动:
          - id/bali-lindy-exchange-2024.md
        - 存档:
          - id/2024.md
      - 日本:
        - 时间线: jp/index.md
        - 按城市划分: jp/by_city.md
        - 主办城市: jp/host_cities.md
        - 已收录活动:
          - jp/tokyo-balboa-weekend-2024.md
          - jp/swing-owl-halloween-2024.md
          - jp/osaka-lindy-exchange-2024.md
          - jp/swing-owl-08-2024.md
          - jp/swing-jack-2024.md
          - jp/yokohama-cross-street-hop-07-2024.md
          - jp/bal-in-tokyo-2024.md
          - jp/chocolate-shake-07-2024.md
          - jp/swingin-n-hoppin-sapporp-2024.md
          - jp/yokohama-cross-street-hop-06-2024.md
          - jp/tomodachi-swing-2024.md
          - jp/swing-owl-06-2024.md
          - jp/chocolate-shake-06-2024.md
          - jp/balboa-lab-tea-party-2024.md
          - jp/chill-balboa-social-2024.md
        - 存档:
          - jp/2024.md
      - 韩国:
        - 时间线: kr/index.md
        - 按城市划分: kr/by_city.md
        - 主办城市: kr/host_cities.md
        - 已收录活动:
          - kr/camp-swing-it-2025.md
          - kr/asia-balboa-exchange-2025.md
          - kr/blues-alive-2025.md
          - kr/savoy-cup-asia-2024.md
          - kr/korean-balboa-weekend-2024.md
          - kr/jump-to-berlin-2024.md
          - kr/seoul-lindy-fest-2024.md
          - kr/bal-hop-2024.md
          - kr/champions-cup-korea-2024.md
          - kr/rhythm-korea-2024.md
        - 存档:
          - kr/2025.md
          - kr/2024.md
      - 泰国:
        - 时间线: th/index.md
        - 按城市划分: th/by_city.md
        - 主办城市: th/host_cities.md
        - 已收录活动:
          - th/breezy-balboa-2025.md
          - th/diga-diga-doo-2024.md
          - th/swing-era-2024.md
          - th/breezy-balboa-2024.md
        - 存档:
          - th/2025.md
          - th/2024.md
      - 土耳其:
        - 时间线: tr/index.md
        - 按城市划分: tr/by_city.md
        - 主办城市: tr/host_cities.md
        - 已收录活动:
          - tr/jumpin-at-istanbul-2025.md
        - 存档:
          - tr/2025.md
      - 台湾:
        - 时间线: tw/index.md
        - 按城市划分: tw/by_city.md
        - 主办城市: tw/host_cities.md
        - 已收录活动:
          - tw/cheek-to-cheek-swing-festival-2025.md
          - tw/what-the-pa-2024.md
        - 存档:
          - tw/2025.md
          - tw/2024.md
    - 欧洲:
      - 比利时:
        - 时间线: be/index.md
        - 按城市划分: be/by_city.md
        - 主办城市: be/host_cities.md
        - 已收录活动:
          - be/boulevard-blues-2024.md
        - 存档:
          - be/2024.md
      - 瑞士:
        - 时间线: ch/index.md
        - 按城市划分: ch/by_city.md
        - 主办城市: ch/host_cities.md
        - 已收录活动:
          - ch/bal-inspiration-2025.md
          - ch/stir-it-2024.md
          - ch/rocky-balberna-2024.md
          - ch/shake-that-lake-2024.md
          - ch/shag-delight-2024.md
        - 存档:
          - ch/2025.md
          - ch/2024.md
      - 捷克:
        - 时间线: cz/index.md
        - 按城市划分: cz/by_city.md
        - 主办城市: cz/host_cities.md
        - 已收录活动:
          - cz/slow-bal-love-2024.md
          - cz/bal-love-2024.md
        - 存档:
          - cz/2024.md
      - 德国:
        - 时间线: de/index.md
        - 按城市划分: de/by_city.md
        - 主办城市: de/host_cities.md
        - 已收录活动:
          - de/swingcake-tubingen-2025.md
          - de/b-t-switch-2025.md
          - de/berlin-balboa-weekend-2025.md
          - de/rock-that-swing-festival-2025.md
          - de/swing-it-berlin-2025.md
          - de/slow-balboa-weekend-munich-2025.md
          - de/xma-swing-2024.md
          - de/autumn-leaves-the-pott-2024.md
          - de/sandy-lewis-workshop-2024.md
          - de/hully-hop-swing-farm-2024.md
          - de/balboa-date-stuttgart-2024.md
          - de/augsburg-boogie-festival-2024.md
          - de/swinging-marzipan-lubeck-2024.md
          - de/swingin-charlie-2024.md
          - de/broadway-swing-2024.md
          - de/mainhatten-shuffle-2024.md
          - de/swing-man-tau-2024.md
          - de/munich-balboa-n-shag-weekend-2024.md
          - de/da-solo-jazz-festival-2024.md
          - de/are-you-syncopated-2024.md
          - de/swingomania-2024.md
          - de/lindy-cake-2024.md
          - de/blues-dance-retreat-2024.md
          - de/flying-feet-stuttgart-2024.md
          - de/boost-lindy-hop-workshop-2024.md
          - de/hully-blues-2024.md
          - de/augsburg-balboa-festival-2024.md
          - de/swing-it-konstanz-2024.md
          - de/hannover-swing-exchange-2024.md
          - de/lindy-hop-trainingslager-2024.md
          - de/shag-ahoi-2024.md
          - de/harvest-moon-swing-dance-camp-2024.md
          - de/velo-swing-festival-2024.md
        - 存档:
          - de/2025.md
          - de/2024.md
      - 丹麦:
        - 时间线: dk/index.md
        - 按城市划分: dk/by_city.md
        - 主办城市: dk/host_cities.md
        - 已收录活动:
          - dk/falling-for-swing-2024.md
          - dk/copenhagen-balboa-weekend-2024.md
          - dk/why-not-aarhus-lindy-exchange-2024.md
        - 存档:
          - dk/2024.md
      - 西班牙:
        - 时间线: es/index.md
        - 按城市划分: es/by_city.md
        - 主办城市: es/host_cities.md
        - 已收录活动:
          - es/barcelona-balboa-festival-2024.md
          - es/espanish-blues-festival-2024.md
          - es/mojo-swing-tropical-fest-2024.md
          - es/swing-fest-malaga-2024.md
          - es/swing-ciudad-real-2024.md
          - es/donosti-belle-swing-festival-2024.md
          - es/cadiz-swing-festival-2024.md
          - es/stomp-your-feet-2024.md
          - es/smile-trio-weekend-2024.md
          - es/calpe-swing-fiesta-2024.md
          - es/swing-a-esgaya-2024.md
          - es/barcelona-shag-festival-2024.md
          - es/the-jump-2024.md
          - es/barcelona-lindy-exchange-2024.md
          - es/swim-out-costa-brava-2024.md
          - es/morella-swing-weekend-2024.md
          - es/jazz-n-swing-gasteiz-festival-2024.md
          - es/festival-swing-monachil-2024.md
          - es/metropoli-fest-2024.md
          - es/sevilla-swing-festival-2024.md
          - es/move-your-bottom-2024.md
        - 存档:
          - es/2024.md
      - 法国:
        - 时间线: fr/index.md
        - 按城市划分: fr/by_city.md
        - 主办城市: fr/host_cities.md
        - 已收录活动:
          - fr/swing-art-festival-2025.md
          - fr/tours-n-swing-2025.md
          - fr/the-battle-2025.md
          - fr/european-balboa-festival-2024.md
          - fr/swingamann-2024.md
          - fr/lyon-swing-festival-2024.md
          - fr/rainy-blues-2024.md
          - fr/toulouse-swing-exchange-2024.md
          - fr/savoie-balboa-festival-2024.md
          - fr/tours-n-balboa-2024.md
          - fr/la-plagne-swing-2024.md
          - fr/summer-camp-blues-week-2024.md
          - fr/summer-camp-lindy-week-2024.md
          - fr/anduze-jazz-dance-camp-2024.md
          - fr/summer-camp-balboa-week-2024.md
        - 存档:
          - fr/2025.md
          - fr/2024.md
      - 希腊:
        - 时间线: gr/index.md
        - 按城市划分: gr/by_city.md
        - 主办城市: gr/host_cities.md
        - 已收录活动:
          - gr/wild-west-festival-2024.md
          - gr/crete-on-the-beat-2024.md
        - 存档:
          - gr/2024.md
      - 意大利:
        - 时间线: it/index.md
        - 按城市划分: it/by_city.md
        - 主办城市: it/host_cities.md
        - 已收录活动:
          - it/sunny-slide-swing-fest-2025.md
          - it/brescia-balboa-series-may-2025.md
          - it/swing-train-festival-2025.md
          - it/brescia-balboa-series-apr-2025.md
          - it/roma-balboa-weekend-2025.md
          - it/brescia-balboa-series-mar-2025.md
          - it/swing-in-roma-2025.md
          - it/brescia-balboa-series-feb-2025.md
          - it/milan-balboa-weekend-2025.md
          - it/tuscany-balboa-weekend-2025.md
          - it/crazy-blues-2025.md
          - it/keep-on-swingin-2025.md
          - it/brescia-balboa-series-jan-2025.md
          - it/brescia-balboa-series-nov-2024.md
          - it/swing-n-milan-2024.md
          - it/brescia-balboa-series-oct-2024.md
          - it/swingala-2024.md
          - it/sicily-swing-fest-2024.md
          - it/balboario-2024.md
          - it/policoro-in-swing-2024.md
          - it/bal-n-lindy-vintage-festival-2024.md
          - it/swing-in-the-amalfi-coast-2024.md
        - 存档:
          - it/2025.md
          - it/2024.md
      - 立陶宛:
        - 时间线: lt/index.md
        - 按城市划分: lt/by_city.md
        - 主办城市: lt/host_cities.md
        - 已收录活动:
          - lt/uptown-rhythm-2025.md
          - lt/vilnius-shag-festival-2024.md
          - lt/all-lithuanian-weekend-2024.md
          - lt/bluesila-2024.md
          - lt/what-a-jazz-summer-camp-2024.md
        - 存档:
          - lt/2025.md
          - lt/2024.md
      - 卢森堡:
        - 时间线: lu/index.md
        - 按城市划分: lu/by_city.md
        - 主办城市: lu/host_cities.md
        - 已收录活动:
          - lu/swing-the-abbey-2024.md
        - 存档:
          - lu/2024.md
      - 荷兰:
        - 时间线: nl/index.md
        - 按城市划分: nl/by_city.md
        - 主办城市: nl/host_cities.md
        - 已收录活动:
          - nl/the-vintage-battle-of-the-bands-2024.md
          - nl/swing-dom-2024.md
          - nl/the-mess-around-2024.md
        - 存档:
          - nl/2024.md
      - 挪威:
        - 时间线: no/index.md
        - 按城市划分: no/by_city.md
        - 主办城市: no/host_cities.md
        - 已收录活动:
          - no/bal-heim-2025.md
          - no/winter-jump-2025.md
          - no/scandinavian-shuffle-2025.md
          - no/vintage-swing-night-2024.md
          - no/swing-brother-swing-2024.md
          - no/oslo-balboa-weekend-2024.md
          - no/o-slow-2024.md
          - no/slow-balboa-boost-2024.md
          - no/boogie-feets-festival-2024.md
        - 存档:
          - no/2025.md
          - no/2024.md
      - 波兰:
        - 时间线: pl/index.md
        - 按城市划分: pl/by_city.md
        - 主办城市: pl/host_cities.md
        - 已收录活动:
          - pl/lindy-szaus-birthday-jam-2025.md
          - pl/dragon-swing-festival-2024.md
          - pl/rock-the-balboa-2024.md
          - pl/lindy-hop-non-stop-2024.md
          - pl/lindy-szaus-birthday-jam-2024.md
        - 存档:
          - pl/2025.md
          - pl/2024.md
      - 俄罗斯:
        - 时间线: ru/index.md
        - 按城市划分: ru/by_city.md
        - 主办城市: ru/host_cities.md
        - 已收录活动:
          - ru/balboa-dacha-2025.md
          - ru/moscow-comes-around-2024.md
        - 存档:
          - ru/2025.md
          - ru/2024.md
      - 瑞典:
        - 时间线: se/index.md
        - 按城市划分: se/by_city.md
        - 主办城市: se/host_cities.md
        - 已收录活动:
          - se/the-snowball-2024.md
          - se/gothenburg-queer-lindy-festival-2024.md
          - se/heedman-dance-camp-2024.md
          - se/herrang-dance-camp-2024.md
        - 存档:
          - se/2024.md
      - 斯洛文尼亚:
        - 时间线: si/index.md
        - 按城市划分: si/by_city.md
        - 主办城市: si/host_cities.md
        - 已收录活动:
          - si/vintage-swing-festival-2024.md
          - si/haniBal-balboa-festival-2024.md
        - 存档:
          - si/2024.md
      - 英国:
        - 时间线: uk/index.md
        - 按城市划分: uk/by_city.md
        - 主办城市: uk/host_cities.md
        - 已收录活动:
          - uk/lindy-in-the-sky-with-diamonds-2025.md
          - uk/the-savoy-jazz-jam-2024.md
          - uk/cambridge-lindy-exchange-2024.md
          - uk/atomic-cocktail-2024.md
          - uk/swing-city-brighton-weekend-2024.md
          - uk/northern-slow-bal-celebration-2024.md
          - uk/mersey-swing-smackdown-2024.md
          - uk/fast-feet-festival-2024.md
          - uk/belta-blues-2024.md
          - uk/edinburgh-lindy-exchange-2024.md
          - uk/nighthawks-summer-weekender-2024.md
          - uk/bal-break-at-the-livermead-cliff-2024.md
          - uk/hep-to-the-hive-2024.md
        - 存档:
          - uk/2025.md
          - uk/2024.md
    - 大洋洲:
      - 澳大利亚:
        - 时间线: au/index.md
        - 按城市划分: au/by_city.md
        - 主办城市: au/host_cities.md
        - 已收录活动:
          - au/hullabaloo-2025.md
          - au/jurassic-bal-2025.md
          - au/the-adelaide-lindy-exchange-2025.md
          - au/remy-n-ramona-weekend-2024.md
          - au/melbourne-lindy-exchange-2024.md
          - au/lindy-rovale-2024.md
          - au/brisbane-balboa-weekend-2024.md
          - au/boogie-down-south-2024.md
          - au/spring-mini-blues-weekend-2024.md
          - au/sydney-lindy-exchange-2024.md
          - au/gold-coast-lindy-fest-2024.md
          - au/winter-swing-festival-2024.md
          - au/brisbane-swing-thing-2024.md
          - au/jurassic-bal-2024.md
        - 存档:
          - au/2025.md
          - au/2024.md
  - 组织: https://swing.kids/zh-Hans
  - references.md
  - 更新日志: https://github.com/swingdance/events/commits/main/
  - 关于:
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: https://swing.kids/zh-Hans/submit
