INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"
        font_family: Noto Sans SC

site_description: '一些世界各地的摇摆舞活动相关信息收录。'
nav:
  - 首页:
    - 时间线: index.md
    - 标签: tags.md
    - 存档:
      - '2025': 2025.md
      - '2024': 2024.md
  - 地区:
    - 所有: regions.md
    - 美洲:
      - en_US • 美国:
        - 时间线: en_US/index.md
        - 按城市划分: en_US/by_city.md
        - 主办城市: en_US/host_cities.md
        - 已收录活动:
          - en_US/hot-rhythm-holiday-2025.md
          - en_US/breat-lakes-balboa-escape-2024.md
          - en_US/bal-week-2024.md
        - 存档:
          - en_US/2025.md
          - en_US/2024.md
      - es_MX • 墨西哥:
        - 时间线: es_MX/index.md
        - 按城市划分: es_MX/by_city.md
        - 主办城市: es_MX/host_cities.md
        - 已收录活动:
          - es_MX/lindy-n-balboa-maya-fest-2024.md
        - 存档:
          - es_MX/2024.md
    - 亚洲:
      - ja_JP • 日本:
        - 时间线: ja_JP/index.md
        - 按城市划分: ja_JP/by_city.md
        - 主办城市: ja_JP/host_cities.md
        - 已收录活动:
          - ja_JP/tokyo-balboa-weekend-2024.md
          - ja_JP/swing-owl-halloween-2024.md
          - ja_JP/osaka-lindy-exchange-2024.md
          - ja_JP/swing-owl-08-2024.md
          - ja_JP/swing-jack-2024.md
          - ja_JP/yokohama-cross-street-hop-07-2024.md
          - ja_JP/bal-in-tokyo-2024.md
          - ja_JP/chocolate-shake-07-2024.md
          - ja_JP/swingin-n-hoppin-sapporp-2024.md
          - ja_JP/yokohama-cross-street-hop-06-2024.md
          - ja_JP/tomodachi-swing-2024.md
          - ja_JP/swing-owl-06-2024.md
          - ja_JP/chocolate-shake-06-2024.md
          - ja_JP/balboa-lab-tea-party-2024.md
          - ja_JP/chill-balboa-social-2024.md
        - 存档:
          - ja_JP/2024.md
      - ko_KR • 韩国:
        - 时间线: ko_KR/index.md
        - 按城市划分: ko_KR/by_city.md
        - 主办城市: ko_KR/host_cities.md
        - 已收录活动:
          - ko_KR/savoy-cup-asia-2024.md
          - ko_KR/korean-balboa-weekend-2024.md
          - ko_KR/champions-cup-korea-2024.md
          - ko_KR/rhythm-korea-2024.md
        - 存档:
          - ko_KR/2024.md
      - th_TH • 泰国:
        - 时间线: th_TH/index.md
        - 按城市划分: th_TH/by_city.md
        - 主办城市: th_TH/host_cities.md
        - 已收录活动:
          - th_TH/diga-diga-doo-2024.md
          - th_TH/breezy-balboa-2024.md
        - 存档:
          - th_TH/2024.md
      - tr_TR • 土耳其:
        - 时间线: tr_TR/index.md
        - 按城市划分: tr_TR/by_city.md
        - 主办城市: tr_TR/host_cities.md
        - 已收录活动:
          - tr_TR/jumpin-at-istanbul-2025.md
        - 存档:
          - tr_TR/2025.md
      - zh_CN • 中国:
        - 时间线: zh_CN/index.md
        - 按城市划分: zh_CN/by_city.md
        - 主办城市: zh_CN/host_cities.md
        - 已收录活动:
          - zh_CN/swingtime-ball-2024.md
          - zh_CN/shanghai-balboa-weekend-2024.md
          - zh_CN/womens-jazzination-2024.md
          - zh_CN/beijing-blues-bush-2024.md
          - zh_CN/westlake-swing-carnival-2024.md
          - zh_CN/blues-heat-2024.md
          - zh_CN/swing-feast-2024.md
          - zh_CN/jazz-do-it-2024.md
          - zh_CN/funs-swing-exchange-2024.md
          - zh_CN/bal-in-beijing-2024.md
          - zh_CN/balboa-festival-2024.md
          - zh_CN/jump-for-joy-2024.md
          - zh_CN/dragon-boat-swing-camp-2024.md
          - zh_CN/dali-lalla-n-sunny-workshop-2024.md
          - zh_CN/vasu-n-nan-balboa-workshop-2024.md
          - zh_CN/nanjing-lindy-festival-2024.md
          - zh_CN/xiamen-kiki-house-african-dance-workshop-2024.md
          - zh_CN/awozi-n-lis-fuzhou-workshop-2024.md
          - zh_CN/shanghai-blues-camp-2024.md
          - zh_CN/beijing-balboa-fever-2024.md
          - zh_CN/jumping-swing-2024.md
          - zh_CN/balboa-spring-camp-2024.md
          - zh_CN/bouncy-chengdu-2024.md
          - zh_CN/beijing-sharon-davis-workshop-2024.md
          - zh_CN/lindy-hotpot-2024.md
          - zh_CN/xiamen-awozi-n-lis-workshop-2024.md
          - zh_CN/groove-the-blusy-bay-2024.md
          - zh_CN/all-balboa-exchange-2024.md
          - zh_CN/xiamen-jiaming-n-wanyuan-workshop-2024.md
          - zh_CN/beijing-balboa-travel-2024.md
        - 存档:
          - zh_CN/2024.md
      - zh_HK • 香港:
        - 时间线: zh_HK/index.md
        - 按城市划分: zh_HK/by_city.md
        - 主办城市: zh_HK/host_cities.md
        - 已收录活动:
          - zh_HK/harbourside-swing-fest-2025.md
          - zh_HK/vasu-n-xinru-balboa-weekend-2024.md
          - zh_HK/harbourside-swing-fest-2024.md
        - 存档:
          - zh_HK/2025.md
          - zh_HK/2024.md
      - zh_TW • 台湾:
        - 时间线: zh_TW/index.md
        - 按城市划分: zh_TW/by_city.md
        - 主办城市: zh_TW/host_cities.md
        - 已收录活动:
          - zh_TW/what-the-pa-2024.md
        - 存档:
          - zh_TW/2024.md
    - 欧洲:
      - cs_CZ • 捷克:
        - 时间线: cs_CZ/index.md
        - 按城市划分: cs_CZ/by_city.md
        - 主办城市: cs_CZ/host_cities.md
        - 已收录活动:
          - cs_CZ/slow-bal-love-2024.md
          - cs_CZ/bal-love-2024.md
        - 存档:
          - cs_CZ/2024.md
      - pl_PL • 波兰:
        - 时间线: pl_PL/index.md
        - 按城市划分: pl_PL/by_city.md
        - 主办城市: pl_PL/host_cities.md
        - 已收录活动:
          - pl_PL/dragon-swing-festival-2024.md
        - 存档:
          - pl_PL/2024.md
      - sv_SE • 瑞典:
        - 时间线: sv_SE/index.md
        - 按城市划分: sv_SE/by_city.md
        - 主办城市: sv_SE/host_cities.md
        - 已收录活动:
          - sv_SE/the-snowball-2024.md
          - sv_SE/heedman-dance-camp-2024.md
          - sv_SE/herrang-dance-camp-2024.md
        - 存档:
          - sv_SE/2024.md
  - 组织: https://swing.kids
  - 更新日志: https://github.com/swingdance/events/commits/main/
  - 关于:
    - references.md
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: submit.md
