INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

site_description: 'A collection of swing dance events from around the world.'
nav:
  - 首页:
    - 时间线: index.md
    - 标签: tags.md
    - 存档:
      - 2024: 2024/index.md
  - 地区:
    - 所有: 2024/regions.md
    - 亚洲:
      - ja_JP • 日本:
        - 时间线: 2024/ja_JP/index.md
        - 按城市划分: 2024/ja_JP/cities.md
        - 今年所有主办城市:
          - 2024/ja_JP/Sapporo.md
          - 2024/ja_JP/Tokyo.md
          - 2024/ja_JP/Yokohama.md
        - 今年所有活动:
          - 2024/ja_JP/tokyo-balboa-weekend.md
          - 2024/ja_JP/swing-owl-halloween.md
          - 2024/ja_JP/swing-owl-08.md
          - 2024/ja_JP/swing-jack.md
          - 2024/ja_JP/yokohama-cross-street-hop.md
          - 2024/ja_JP/bal-in-tokyo.md
          - 2024/ja_JP/chocolate-shake-07.md
          - 2024/ja_JP/swingin-n-hoppin-sapporp.md
          - 2024/ja_JP/yokohama-cross-street-hop.md
          - 2024/ja_JP/tomodachi-swing.md
          - 2024/ja_JP/swing-owl-06.md
          - 2024/ja_JP/chocolate-shake-06.md
          - 2024/ja_JP/balboa-lab-tea-party.md
          - 2024/ja_JP/chill-balboa-social.md
      - ko_KR • 韩国:
        - 时间线: 2024/ko_KR/index.md
        - 按城市划分: 2024/ko_KR/cities.md
        - 今年所有主办城市:
          - 2024/ko_KR/Seoul.md
        - 今年所有活动:
          - 2024/ko_KR/savoy-cup-asia.md
          - 2024/ko_KR/champions-cup-korea.md
          - 2024/ko_KR/rhythm-korea.md
      - th_TH • 泰国:
        - 时间线: 2024/th_TH/index.md
        - 按城市划分: 2024/th_TH/cities.md
        - 今年所有主办城市:
          - 2024/th_TH/Bangkok.md
          - 2024/th_TH/Prachuap Khiri Khan.md
        - 今年所有活动:
          - 2024/th_TH/diga-diga-doo.md
          - 2024/th_TH/breezy-balboa.md
      - zh_CN • 中国:
        - 时间线: 2024/zh_CN/index.md
        - 按城市划分: 2024/zh_CN/cities.md
        - 今年所有主办城市:
          - 2024/zh_CN/Beijing.md
          - 2024/zh_CN/Chongqing.md
          - 2024/zh_CN/Fujian.md
          - 2024/zh_CN/Guangdong.md
          - 2024/zh_CN/Hunan.md
          - 2024/zh_CN/Jiangsu.md
          - 2024/zh_CN/Shanghai.md
          - 2024/zh_CN/Sichuan.md
          - 2024/zh_CN/Yunnan.md
        - 今年所有活动:
          - 2024/zh_CN/shanghai-balboa-weekend.md
          - 2024/zh_CN/womens-jazzination.md
          - 2024/zh_CN/beijing-blues-bush.md
          - 2024/zh_CN/swing-feast.md
          - 2024/zh_CN/jazz-do-it.md
          - 2024/zh_CN/funs-swing-exchange.md
          - 2024/zh_CN/balboa-festival.md
          - 2024/zh_CN/jump-for-joy.md
          - 2024/zh_CN/dragon-boat-swing-camp.md
          - 2024/zh_CN/dali-lalla-n-sunny-workshop.md
          - 2024/zh_CN/vasu-n-nan-balboa-workshop.md
          - 2024/zh_CN/nanjing-lindy-festival.md
          - 2024/zh_CN/xiamen-kiki-house-african-dance-workshop.md
          - 2024/zh_CN/awozi-n-lis-fuzhou-workshop.md
          - 2024/zh_CN/shanghai-blues-camp.md
          - 2024/zh_CN/beijing-balboa-fever.md
          - 2024/zh_CN/jumping-swing.md
          - 2024/zh_CN/balboa-spring-camp.md
          - 2024/zh_CN/bouncy-chengdu.md
          - 2024/zh_CN/beijing-sharon-davis-workshop.md
          - 2024/zh_CN/lindy-hotpot.md
          - 2024/zh_CN/xiamen-awozi-n-lis-workshop.md
          - 2024/zh_CN/groove-the-blusy-bay.md
          - 2024/zh_CN/all-balboa-exchange.md
          - 2024/zh_CN/xiamen-jiaming-n-wanyuan-workshop.md
          - 2024/zh_CN/beijing-balboa-travel.md
      - zh_HK • 香港:
        - 时间线: 2024/zh_HK/index.md
        - 按城市划分: 2024/zh_HK/cities.md
        - 今年所有主办城市:
          - 2024/zh_HK/HK.md
        - 今年所有活动:
          - 2024/zh_HK/harbourside-swing-fest.md
      - zh_TW • 台湾:
        - 时间线: 2024/zh_TW/index.md
        - 按城市划分: 2024/zh_TW/cities.md
        - 今年所有主办城市:
          - 2024/zh_TW/Taipei.md
        - 今年所有活动:
          - 2024/zh_TW/what-the-pa.md
    - 欧洲:
      - sv_SE • 瑞典:
        - 时间线: 2024/sv_SE/index.md
        - 按城市划分: 2024/sv_SE/cities.md
        - 今年所有主办城市:
          - 2024/sv_SE/Stockholm.md
        - 今年所有活动:
          - 2024/sv_SE/herrang-dance-camp.md
  - 组织: https://swing.kids
  - 更新日志: https://github.com/swingdance/events/commits/main/
  - 关于:
    - references.md
    - support.md
    - 隐私与条款:
      - privacy.md
      - terms.md
  - + 添加组织/活动: submit.md
