INHERIT: '../base.yml'

docs_dir: '../../src/zh-Hans'
site_dir: '../../build/zh-Hans'

theme:
  name: material
  language: zh

site_description: 'A collection of swing dance events from around the world.'
nav:
  - 首页: index.md
  - 标签: tags.md
