site_name: Swing News
site_url: https://swing.news
site_description: A collection of swing dance events from around the world.
site_author: Kjuly
copyright: Copyright &copy; 2024 <a href="https://kjuly.com" target="blank">Kaijie Yu</a>

use_directory_urls: true

exclude_docs: |
  .*
  tmp/

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  not_found: warn

theme:
  name: material
  language: en
  custom_dir: '../../overrides'
  logo: assets/logo.png
  favicon: assets/favicon.png
  # icon:
  #   admonition:
  #     note: fontawesome/solid/map-location-dot
  # navigation_depth: 1
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
      primary: white
      accent: deep orange

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black
      accent: orange

  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    # - navigation.expand
    - navigation.prune
    # - navigation.instant.progress
    # - header.autohide
    - navigation.footer
    - toc.follow

plugins:
  - search
  - tags:
      tags_file: tags.md
  # - optimize

markdown_extensions:
  - toc:
      toc_depth: 3
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - tables
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - 'css/extra.css'

extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 简体中文
      link: /zh-Hans/
      lang: zh

  status:
    timeline: Index page of Event Timeline.
    city: Index page of Events by City.
    tag: Tags.
    references: References.
    help: Help & Feedback.
    privacy: Privacy Policy.
    terms: Terms & Conditions.

  social:
    - icon: fontawesome/solid/user-group
      link: https://swing.kids
      name: Swing Kids
    - icon: fontawesome/brands/github
      link: https://github.com/swingdance
      name: Source Code on Github
    
