INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

site_description: 'A collection of swing dance events from around the world.'
nav:
  - Home:
    - Timeline: index.md
    - Tags: tags.md
    - Archives:
      - 2024: 2024/index.md
  - Regions:
    - All: 2024/regions.md
    - Asia:
      - ja_JP • Japan:
        - Timeline: 2024/ja_JP/index.md
        - Events by City: 2024/ja_JP/cities.md
        - All Host Cities This Year:
          - 2024/ja_JP/Sapporo.md
          - 2024/ja_JP/Tokyo.md
          - 2024/ja_JP/Yokohama.md
        - All Events This Year:
          - 2024/ja_JP/tokyo-balboa-weekend.md
          - 2024/ja_JP/swing-owl-halloween.md
          - 2024/ja_JP/swing-owl-08.md
          - 2024/ja_JP/swing-jack.md
          - 2024/ja_JP/yokohama-cross-street-hop.md
          - 2024/ja_JP/bal-in-tokyo.md
          - 2024/ja_JP/chocolate-shake-07.md
          - 2024/ja_JP/swingin-n-hoppin-sapporp.md
          - 2024/ja_JP/yokohama-cross-street-hop.md
          - 2024/ja_JP/tomodachi-swing.md
          - 2024/ja_JP/swing-owl-06.md
          - 2024/ja_JP/chocolate-shake-06.md
          - 2024/ja_JP/balboa-lab-tea-party.md
          - 2024/ja_JP/chill-balboa-social.md
      - ko_KR • South Korea:
        - Timeline: 2024/ko_KR/index.md
        - Events by City: 2024/ko_KR/cities.md
        - All Host Cities This Year:
          - 2024/ko_KR/Seoul.md
        - All Events This Year:
          - 2024/ko_KR/savoy-cup-asia.md
          - 2024/ko_KR/champions-cup-korea.md
          - 2024/ko_KR/rhythm-korea.md
      - th_TH • Thailand:
        - Timeline: 2024/th_TH/index.md
        - Events by City: 2024/th_TH/cities.md
        - All Host Cities This Year:
          - 2024/th_TH/Bangkok.md
          - 2024/th_TH/Prachuap Khiri Khan.md
        - All Events This Year:
          - 2024/th_TH/diga-diga-doo.md
          - 2024/th_TH/breezy-balboa.md
      - zh_CN • China:
        - Timeline: 2024/zh_CN/index.md
        - Events by City: 2024/zh_CN/cities.md
        - All Host Cities This Year:
          - 2024/zh_CN/Beijing.md
          - 2024/zh_CN/Chongqing.md
          - 2024/zh_CN/Fujian.md
          - 2024/zh_CN/Guangdong.md
          - 2024/zh_CN/Hunan.md
          - 2024/zh_CN/Jiangsu.md
          - 2024/zh_CN/Shanghai.md
          - 2024/zh_CN/Sichuan.md
          - 2024/zh_CN/Yunnan.md
          - 2024/zh_CN/Zhejiang.md
        - All Events This Year:
          - 2024/zh_CN/shanghai-balboa-weekend.md
          - 2024/zh_CN/womens-jazzination.md
          - 2024/zh_CN/beijing-blues-bush.md
          - 2024/zh_CN/westlake-swing-carnival.md
          - 2024/zh_CN/swing-feast.md
          - 2024/zh_CN/jazz-do-it.md
          - 2024/zh_CN/funs-swing-exchange.md
          - 2024/zh_CN/balboa-festival.md
          - 2024/zh_CN/jump-for-joy.md
          - 2024/zh_CN/dragon-boat-swing-camp.md
          - 2024/zh_CN/dali-lalla-n-sunny-workshop.md
          - 2024/zh_CN/vasu-n-nan-balboa-workshop.md
          - 2024/zh_CN/nanjing-lindy-festival.md
          - 2024/zh_CN/xiamen-kiki-house-african-dance-workshop.md
          - 2024/zh_CN/awozi-n-lis-fuzhou-workshop.md
          - 2024/zh_CN/shanghai-blues-camp.md
          - 2024/zh_CN/beijing-balboa-fever.md
          - 2024/zh_CN/jumping-swing.md
          - 2024/zh_CN/balboa-spring-camp.md
          - 2024/zh_CN/bouncy-chengdu.md
          - 2024/zh_CN/beijing-sharon-davis-workshop.md
          - 2024/zh_CN/lindy-hotpot.md
          - 2024/zh_CN/xiamen-awozi-n-lis-workshop.md
          - 2024/zh_CN/groove-the-blusy-bay.md
          - 2024/zh_CN/all-balboa-exchange.md
          - 2024/zh_CN/xiamen-jiaming-n-wanyuan-workshop.md
          - 2024/zh_CN/beijing-balboa-travel.md
      - zh_HK • Hong Kong:
        - Timeline: 2024/zh_HK/index.md
        - Events by City: 2024/zh_HK/cities.md
        - All Host Cities This Year:
          - 2024/zh_HK/HK.md
        - All Events This Year:
          - 2024/zh_HK/vasu-n-xinru-balboa-weekend.md
          - 2024/zh_HK/harbourside-swing-fest.md
      - zh_TW • Taiwan:
        - Timeline: 2024/zh_TW/index.md
        - Events by City: 2024/zh_TW/cities.md
        - All Host Cities This Year:
          - 2024/zh_TW/Taipei.md
        - All Events This Year:
          - 2024/zh_TW/what-the-pa.md
    - Europe:
      - sv_SE • Sweden:
        - Timeline: 2024/sv_SE/index.md
        - Events by City: 2024/sv_SE/cities.md
        - All Host Cities This Year:
          - 2024/sv_SE/Lulea.md
          - 2024/sv_SE/Stockholm.md
        - All Events This Year:
          - 2024/sv_SE/heedman-dance-camp.md
          - 2024/sv_SE/herrang-dance-camp.md
  - Orgs: https://swing.kids
  - Changelogs: https://github.com/swingdance/events/commits/main/
  - About:
    - references.md
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: submit.md
