INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"

site_description: 'A collection of swing dance events from around the world.'
nav:
  - Home:
    - Timeline: index.md
    - Tags: tags.md
    - Archives:
      - '2025': 2025.md
      - '2024': 2024.md
  - Regions:
    - All: regions.md
    - America:
      - America:
        - Timeline: en_US/index.md
        - Events by City: en_US/by_city.md
        - Host Cities: en_US/host_cities.md
        - Collected Events:
          - en_US/hot-rhythm-holiday-2025.md
          - en_US/breat-lakes-balboa-escape-2024.md
          - en_US/bal-week-2024.md
        - Archives:
          - en_US/2025.md
          - en_US/2024.md
      - Mexico:
        - Timeline: es_MX/index.md
        - Events by City: es_MX/by_city.md
        - Host Cities: es_MX/host_cities.md
        - Collected Events:
          - es_MX/lindy-n-balboa-maya-fest-2024.md
        - Archives:
          - es_MX/2024.md
    - Asia:
      - Armenia:
        - Timeline: hy_AM/index.md
        - Events by City: hy_AM/by_city.md
        - Host Cities: hy_AM/host_cities.md
        - Collected Events:
          - hy_AM/swing-road-armenia-2024.md
        - Archives:
          - hy_AM/2024.md
      - Indonesia:
        - Timeline: id_ID/index.md
        - Events by City: id_ID/by_city.md
        - Host Cities: id_ID/host_cities.md
        - Collected Events:
          - id_ID/bali-lindy-exchange-2024.md
        - Archives:
          - id_ID/2024.md
      - Japan:
        - Timeline: ja_JP/index.md
        - Events by City: ja_JP/by_city.md
        - Host Cities: ja_JP/host_cities.md
        - Collected Events:
          - ja_JP/tokyo-balboa-weekend-2024.md
          - ja_JP/swing-owl-halloween-2024.md
          - ja_JP/osaka-lindy-exchange-2024.md
          - ja_JP/swing-owl-08-2024.md
          - ja_JP/swing-jack-2024.md
          - ja_JP/yokohama-cross-street-hop-07-2024.md
          - ja_JP/bal-in-tokyo-2024.md
          - ja_JP/chocolate-shake-07-2024.md
          - ja_JP/swingin-n-hoppin-sapporp-2024.md
          - ja_JP/yokohama-cross-street-hop-06-2024.md
          - ja_JP/tomodachi-swing-2024.md
          - ja_JP/swing-owl-06-2024.md
          - ja_JP/chocolate-shake-06-2024.md
          - ja_JP/balboa-lab-tea-party-2024.md
          - ja_JP/chill-balboa-social-2024.md
        - Archives:
          - ja_JP/2024.md
      - South Korea:
        - Timeline: ko_KR/index.md
        - Events by City: ko_KR/by_city.md
        - Host Cities: ko_KR/host_cities.md
        - Collected Events:
          - ko_KR/savoy-cup-asia-2024.md
          - ko_KR/korean-balboa-weekend-2024.md
          - ko_KR/seoul-lindy-fest-2024.md
          - ko_KR/bal-hop-2024.md
          - ko_KR/champions-cup-korea-2024.md
          - ko_KR/rhythm-korea-2024.md
        - Archives:
          - ko_KR/2024.md
      - Thailand:
        - Timeline: th_TH/index.md
        - Events by City: th_TH/by_city.md
        - Host Cities: th_TH/host_cities.md
        - Collected Events:
          - th_TH/diga-diga-doo-2024.md
          - th_TH/swing-era-2024.md
          - th_TH/breezy-balboa-2024.md
        - Archives:
          - th_TH/2024.md
      - Turkey:
        - Timeline: tr_TR/index.md
        - Events by City: tr_TR/by_city.md
        - Host Cities: tr_TR/host_cities.md
        - Collected Events:
          - tr_TR/jumpin-at-istanbul-2025.md
        - Archives:
          - tr_TR/2025.md
      - China:
        - Timeline: zh_CN/index.md
        - Events by City: zh_CN/by_city.md
        - Host Cities: zh_CN/host_cities.md
        - Collected Events:
          - zh_CN/swingtime-ball-2024.md
          - zh_CN/shanghai-balboa-weekend-2024.md
          - zh_CN/swing-paramount-2024.md
          - zh_CN/womens-jazzination-2024.md
          - zh_CN/claudia-n-coline-workshop-2024.md
          - zh_CN/beijing-blues-bush-2024.md
          - zh_CN/westlake-swing-carnival-2024.md
          - zh_CN/blues-heat-2024.md
          - zh_CN/swing-feast-2024.md
          - zh_CN/blues-workshop-with-taehyeon-2024.md
          - zh_CN/jazz-do-it-2024.md
          - zh_CN/funs-swing-exchange-2024.md
          - zh_CN/bal-in-beijing-2024.md
          - zh_CN/balboa-festival-2024.md
          - zh_CN/jump-for-joy-2024.md
          - zh_CN/dragon-boat-swing-camp-2024.md
          - zh_CN/dali-lalla-n-sunny-workshop-2024.md
          - zh_CN/vasu-n-nan-balboa-workshop-2024.md
          - zh_CN/nanjing-lindy-festival-2024.md
          - zh_CN/xiamen-kiki-house-african-dance-workshop-2024.md
          - zh_CN/awozi-n-lis-fuzhou-workshop-2024.md
          - zh_CN/shanghai-blues-camp-2024.md
          - zh_CN/beijing-balboa-fever-2024.md
          - zh_CN/jumping-swing-2024.md
          - zh_CN/balboa-spring-camp-2024.md
          - zh_CN/bouncy-chengdu-2024.md
          - zh_CN/beijing-sharon-davis-workshop-2024.md
          - zh_CN/lindy-hotpot-2024.md
          - zh_CN/xiamen-awozi-n-lis-workshop-2024.md
          - zh_CN/groove-the-blusy-bay-2024.md
          - zh_CN/all-balboa-exchange-2024.md
          - zh_CN/xiamen-jiaming-n-wanyuan-workshop-2024.md
          - zh_CN/beijing-balboa-travel-2024.md
        - Archives:
          - zh_CN/2024.md
      - Hong Kong:
        - Timeline: zh_HK/index.md
        - Events by City: zh_HK/by_city.md
        - Host Cities: zh_HK/host_cities.md
        - Collected Events:
          - zh_HK/harbourside-swing-fest-2025.md
          - zh_HK/vasu-n-xinru-balboa-weekend-2024.md
          - zh_HK/harbourside-swing-fest-2024.md
        - Archives:
          - zh_HK/2025.md
          - zh_HK/2024.md
      - Taiwan:
        - Timeline: zh_TW/index.md
        - Events by City: zh_TW/by_city.md
        - Host Cities: zh_TW/host_cities.md
        - Collected Events:
          - zh_TW/what-the-pa-2024.md
        - Archives:
          - zh_TW/2024.md
    - Europe:
      - Czechia:
        - Timeline: cs_CZ/index.md
        - Events by City: cs_CZ/by_city.md
        - Host Cities: cs_CZ/host_cities.md
        - Collected Events:
          - cs_CZ/slow-bal-love-2024.md
          - cs_CZ/bal-love-2024.md
        - Archives:
          - cs_CZ/2024.md
      - Spain:
        - Timeline: es_ES/index.md
        - Events by City: es_ES/by_city.md
        - Host Cities: es_ES/host_cities.md
        - Collected Events:
          - es_ES/barcelona-balboa-festival-2024.md
          - es_ES/espanish-blues-festival-2024.md
          - es_ES/mojo-swing-tropical-fest-2024.md
          - es_ES/swing-fest-malaga-2024.md
          - es_ES/swing-ciudad-real-2024.md
          - es_ES/donosti-belle-swing-festival-2024.md
          - es_ES/cadiz-swing-festival-2024.md
          - es_ES/stomp-your-feet-2024.md
          - es_ES/calpe-swing-fiesta-2024.md
          - es_ES/swing-a-esgaya-2024.md
          - es_ES/barcelona-shag-festival-2024.md
          - es_ES/the-jump-2024.md
          - es_ES/barcelona-lindy-exchange-2024.md
          - es_ES/swim-out-costa-brava-2024.md
          - es_ES/morella-swing-weekend-2024.md
          - es_ES/jazz-n-swing-gasteiz-festival-2024.md
          - es_ES/festival-swing-monachil-2024.md
          - es_ES/metropoli-fest-2024.md
          - es_ES/sevilla-swing-festival-2024.md
          - es_ES/move-your-bottom-2024.md
        - Archives:
          - es_ES/2024.md
      - Poland:
        - Timeline: pl_PL/index.md
        - Events by City: pl_PL/by_city.md
        - Host Cities: pl_PL/host_cities.md
        - Collected Events:
          - pl_PL/dragon-swing-festival-2024.md
        - Archives:
          - pl_PL/2024.md
      - Russia:
        - Timeline: ru_RU/index.md
        - Events by City: ru_RU/by_city.md
        - Host Cities: ru_RU/host_cities.md
        - Collected Events:
          - ru_RU/moscow-comes-around-2024.md
        - Archives:
          - ru_RU/2024.md
      - Sweden:
        - Timeline: sv_SE/index.md
        - Events by City: sv_SE/by_city.md
        - Host Cities: sv_SE/host_cities.md
        - Collected Events:
          - sv_SE/the-snowball-2024.md
          - sv_SE/heedman-dance-camp-2024.md
          - sv_SE/herrang-dance-camp-2024.md
        - Archives:
          - sv_SE/2024.md
  - Orgs: https://swing.kids
  - Changelogs: https://github.com/swingdance/events/commits/main/
  - About:
    - references.md
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: submit.md
