INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"

site_description: 'A collection of swing dance events from around the world.'
nav:
  - Home:
    - Timeline: index.md
    - Tags: tags.md
    - Archives:
      - '2025': 2025.md
      - '2024': 2024.md
  - Regions:
    - All: regions.md
    - America:
      - Canada:
        - Timeline: en_CA/index.md
        - Events by City: en_CA/by_city.md
        - Host Cities: en_CA/host_cities.md
        - Collected Events:
          - en_CA/capital-city-stomp-2024.md
          - en_CA/cats-corner-exchange-2024.md
          - en_CA/vancouver-balboa-mini-fest-2024.md
          - en_CA/lindy-harvest-2024.md
          - en_CA/rhythm-city-mess-around-2024.md
          - en_CA/stardust-festival-2024.md
        - Archives:
          - en_CA/2024.md
      - United States:
        - Timeline: en_US/index.md
        - Events by City: en_US/by_city.md
        - Host Cities: en_US/host_cities.md
        - Collected Events:
          - en_US/hot-rhythm-holiday-2025.md
          - en_US/california-balboa-classic-2025.md
          - en_US/stormy-weather-jazz-festival-2024.md
          - en_US/hot-jazz-jamboree-2024.md
          - en_US/stompology-2024.md
          - en_US/breaking-bal-swing-n-blues-weekend-2024.md
          - en_US/emerald-city-blues-festival-2024.md
          - en_US/blues-muse-2024.md
          - en_US/stl-getdown-2024.md
          - en_US/great-lakes-balboa-escape-2024.md
          - en_US/new-york-lindy-exchange-2024.md
          - en_US/lindy-on-the-rocks-2024.md
          - en_US/hot-night-fusion-weekend-2024.md
          - en_US/cowtown-jamborama-2024.md
          - en_US/camp-hollywood-2024.md
          - en_US/the-uptown-swingout-2024.md
          - en_US/swing-out-new-hampshire-2024.md
          - en_US/summer-swing-fest-2024.md
          - en_US/rittenhopalooza-2024.md
          - en_US/cincy-hop-2024.md
          - en_US/flying-home-2024.md
          - en_US/bal-week-2024.md
          - en_US/california-balboa-classic-2024.md
        - Archives:
          - en_US/2025.md
          - en_US/2024.md
      - Chile:
        - Timeline: es_CL/index.md
        - Events by City: es_CL/by_city.md
        - Host Cities: es_CL/host_cities.md
        - Collected Events:
          - es_CL/lindy-poh-2024.md
        - Archives:
          - es_CL/2024.md
      - Mexico:
        - Timeline: es_MX/index.md
        - Events by City: es_MX/by_city.md
        - Host Cities: es_MX/host_cities.md
        - Collected Events:
          - es_MX/guadalajara-lindy-exchange-2024.md
          - es_MX/lindy-n-balboa-maya-fest-2024.md
          - es_MX/mexico-lindy-querido-2024.md
        - Archives:
          - es_MX/2024.md
    - Asia:
      - Armenia:
        - Timeline: hy_AM/index.md
        - Events by City: hy_AM/by_city.md
        - Host Cities: hy_AM/host_cities.md
        - Collected Events:
          - hy_AM/swing-road-armenia-2024.md
        - Archives:
          - hy_AM/2024.md
      - Indonesia:
        - Timeline: id_ID/index.md
        - Events by City: id_ID/by_city.md
        - Host Cities: id_ID/host_cities.md
        - Collected Events:
          - id_ID/bali-lindy-exchange-2024.md
        - Archives:
          - id_ID/2024.md
      - Japan:
        - Timeline: ja_JP/index.md
        - Events by City: ja_JP/by_city.md
        - Host Cities: ja_JP/host_cities.md
        - Collected Events:
          - ja_JP/tokyo-balboa-weekend-2024.md
          - ja_JP/swing-owl-halloween-2024.md
          - ja_JP/osaka-lindy-exchange-2024.md
          - ja_JP/swing-owl-08-2024.md
          - ja_JP/swing-jack-2024.md
          - ja_JP/yokohama-cross-street-hop-07-2024.md
          - ja_JP/bal-in-tokyo-2024.md
          - ja_JP/chocolate-shake-07-2024.md
          - ja_JP/swingin-n-hoppin-sapporp-2024.md
          - ja_JP/yokohama-cross-street-hop-06-2024.md
          - ja_JP/tomodachi-swing-2024.md
          - ja_JP/swing-owl-06-2024.md
          - ja_JP/chocolate-shake-06-2024.md
          - ja_JP/balboa-lab-tea-party-2024.md
          - ja_JP/chill-balboa-social-2024.md
        - Archives:
          - ja_JP/2024.md
      - South Korea:
        - Timeline: ko_KR/index.md
        - Events by City: ko_KR/by_city.md
        - Host Cities: ko_KR/host_cities.md
        - Collected Events:
          - ko_KR/savoy-cup-asia-2024.md
          - ko_KR/korean-balboa-weekend-2024.md
          - ko_KR/seoul-lindy-fest-2024.md
          - ko_KR/bal-hop-2024.md
          - ko_KR/champions-cup-korea-2024.md
          - ko_KR/rhythm-korea-2024.md
        - Archives:
          - ko_KR/2024.md
      - Thailand:
        - Timeline: th_TH/index.md
        - Events by City: th_TH/by_city.md
        - Host Cities: th_TH/host_cities.md
        - Collected Events:
          - th_TH/diga-diga-doo-2024.md
          - th_TH/swing-era-2024.md
          - th_TH/breezy-balboa-2024.md
        - Archives:
          - th_TH/2024.md
      - Turkey:
        - Timeline: tr_TR/index.md
        - Events by City: tr_TR/by_city.md
        - Host Cities: tr_TR/host_cities.md
        - Collected Events:
          - tr_TR/jumpin-at-istanbul-2025.md
        - Archives:
          - tr_TR/2025.md
      - China:
        - Timeline: zh_CN/index.md
        - Events by City: zh_CN/by_city.md
        - Host Cities: zh_CN/host_cities.md
        - Collected Events:
          - zh_CN/shanghai-lindy-festival-2024.md
          - zh_CN/swingtime-ball-2024.md
          - zh_CN/shanghai-balboa-weekend-2024.md
          - zh_CN/swing-paramount-2024.md
          - zh_CN/womens-jazzination-2024.md
          - zh_CN/claudia-n-coline-workshop-2024.md
          - zh_CN/beijing-blues-bush-2024.md
          - zh_CN/westlake-swing-carnival-2024.md
          - zh_CN/blues-heat-2024.md
          - zh_CN/swing-feast-2024.md
          - zh_CN/balboa-greater-bay-workshop-2024.md
          - zh_CN/blues-workshop-with-taehyeon-2024.md
          - zh_CN/jazz-do-it-2024.md
          - zh_CN/funs-swing-exchange-2024.md
          - zh_CN/bal-in-beijing-2024.md
          - zh_CN/balboa-festival-2024.md
          - zh_CN/jump-for-joy-2024.md
          - zh_CN/dragon-boat-swing-camp-2024.md
          - zh_CN/dali-lalla-n-sunny-workshop-2024.md
          - zh_CN/vasu-n-nan-balboa-workshop-2024.md
          - zh_CN/nanjing-lindy-festival-2024.md
          - zh_CN/xiamen-kiki-house-african-dance-workshop-2024.md
          - zh_CN/awozi-n-lis-fuzhou-workshop-2024.md
          - zh_CN/shanghai-blues-camp-2024.md
          - zh_CN/beijing-balboa-fever-2024.md
          - zh_CN/jumping-swing-2024.md
          - zh_CN/balboa-spring-camp-2024.md
          - zh_CN/bouncy-chengdu-2024.md
          - zh_CN/beijing-sharon-davis-workshop-2024.md
          - zh_CN/lindy-hotpot-2024.md
          - zh_CN/xiamen-awozi-n-lis-workshop-2024.md
          - zh_CN/groove-the-blusy-bay-2024.md
          - zh_CN/all-balboa-exchange-2024.md
          - zh_CN/xiamen-jiaming-n-wanyuan-workshop-2024.md
          - zh_CN/beijing-balboa-travel-2024.md
        - Archives:
          - zh_CN/2024.md
      - Hong Kong:
        - Timeline: zh_HK/index.md
        - Events by City: zh_HK/by_city.md
        - Host Cities: zh_HK/host_cities.md
        - Collected Events:
          - zh_HK/harbourside-swing-fest-2025.md
          - zh_HK/vasu-n-xinru-balboa-weekend-2024.md
          - zh_HK/harbourside-swing-fest-2024.md
        - Archives:
          - zh_HK/2025.md
          - zh_HK/2024.md
      - Taiwan:
        - Timeline: zh_TW/index.md
        - Events by City: zh_TW/by_city.md
        - Host Cities: zh_TW/host_cities.md
        - Collected Events:
          - zh_TW/what-the-pa-2024.md
        - Archives:
          - zh_TW/2024.md
    - Europe:
      - Czechia:
        - Timeline: cs_CZ/index.md
        - Events by City: cs_CZ/by_city.md
        - Host Cities: cs_CZ/host_cities.md
        - Collected Events:
          - cs_CZ/slow-bal-love-2024.md
          - cs_CZ/bal-love-2024.md
        - Archives:
          - cs_CZ/2024.md
      - Denmark:
        - Timeline: da_DK/index.md
        - Events by City: da_DK/by_city.md
        - Host Cities: da_DK/host_cities.md
        - Collected Events:
          - da_DK/copenhagen-balboa-weekend-2024.md
          - da_DK/why-not-aarhus-lindy-exchange-2024.md
        - Archives:
          - da_DK/2024.md
      - Switzerland:
        - Timeline: de_CH/index.md
        - Events by City: de_CH/by_city.md
        - Host Cities: de_CH/host_cities.md
        - Collected Events:
          - de_CH/bal-inspiration-2025.md
          - de_CH/stir-it-2024.md
          - de_CH/rocky-balberna-2024.md
          - de_CH/shake-that-lake-2024.md
          - de_CH/shag-delight-2024.md
        - Archives:
          - de_CH/2025.md
          - de_CH/2024.md
      - Germany:
        - Timeline: de_DE/index.md
        - Events by City: de_DE/by_city.md
        - Host Cities: de_DE/host_cities.md
        - Collected Events:
          - de_DE/swingcake-tubingen-2025.md
          - de_DE/b-t-switch-2025.md
          - de_DE/berlin-balboa-weekend-2025.md
          - de_DE/rock-that-swing-festival-2025.md
          - de_DE/swing-it-berlin-2025.md
          - de_DE/slow-balboa-weekend-munich-2025.md
          - de_DE/xma-swing-2024.md
          - de_DE/autumn-leaves-the-pott-2024.md
          - de_DE/sandy-lewis-workshop-2024.md
          - de_DE/hully-hop-swing-farm-2024.md
          - de_DE/balboa-date-stuttgart-2024.md
          - de_DE/augsburg-boogie-festival-2024.md
          - de_DE/swinging-marzipan-lubeck-2024.md
          - de_DE/swingin-charlie-2024.md
          - de_DE/broadway-swing-2024.md
          - de_DE/mainhatten-shuffle-2024.md
          - de_DE/swing-man-tau-2024.md
          - de_DE/munich-balboa-n-shag-weekend-2024.md
          - de_DE/da-solo-jazz-festival-2024.md
          - de_DE/are-you-syncopated-2024.md
          - de_DE/swingomania-2024.md
          - de_DE/lindy-cake-2024.md
          - de_DE/blues-dance-retreat-2024.md
          - de_DE/flying-feet-stuttgart-2024.md
          - de_DE/boost-lindy-hop-workshop-2024.md
          - de_DE/hully-blues-2024.md
          - de_DE/augsburg-balboa-festival-2024.md
          - de_DE/swing-it-konstanz-2024.md
          - de_DE/hannover-swing-exchange-2024.md
          - de_DE/lindy-hop-trainingslager-2024.md
          - de_DE/shag-ahoi-2024.md
          - de_DE/harvest-moon-swing-dance-camp-2024.md
          - de_DE/velo-swing-festival-2024.md
        - Archives:
          - de_DE/2025.md
          - de_DE/2024.md
      - Greece:
        - Timeline: el_GR/index.md
        - Events by City: el_GR/by_city.md
        - Host Cities: el_GR/host_cities.md
        - Collected Events:
          - el_GR/wild-west-festival-2024.md
          - el_GR/crete-on-the-beat-2024.md
        - Archives:
          - el_GR/2024.md
      - United Kingdom:
        - Timeline: en_GB/index.md
        - Events by City: en_GB/by_city.md
        - Host Cities: en_GB/host_cities.md
        - Collected Events:
          - en_GB/lindy-in-the-sky-with-diamonds-2025.md
          - en_GB/the-savoy-jazz-jam-2024.md
          - en_GB/cambridge-lindy-exchange-2024.md
          - en_GB/atomic-cocktail-2024.md
          - en_GB/swing-city-brighton-weekend-2024.md
          - en_GB/northern-slow-bal-celebration-2024.md
          - en_GB/mersey-swing-smackdown-2024.md
          - en_GB/fast-feet-festival-2024.md
          - en_GB/belta-blues-2024.md
          - en_GB/edinburgh-lindy-exchange-2024.md
          - en_GB/nighthawks-summer-weekender-2024.md
          - en_GB/bal-break-at-the-livermead-cliff-2024.md
          - en_GB/hep-to-the-hive-2024.md
        - Archives:
          - en_GB/2025.md
          - en_GB/2024.md
      - Spain:
        - Timeline: es_ES/index.md
        - Events by City: es_ES/by_city.md
        - Host Cities: es_ES/host_cities.md
        - Collected Events:
          - es_ES/barcelona-balboa-festival-2024.md
          - es_ES/espanish-blues-festival-2024.md
          - es_ES/mojo-swing-tropical-fest-2024.md
          - es_ES/swing-fest-malaga-2024.md
          - es_ES/swing-ciudad-real-2024.md
          - es_ES/donosti-belle-swing-festival-2024.md
          - es_ES/cadiz-swing-festival-2024.md
          - es_ES/stomp-your-feet-2024.md
          - es_ES/calpe-swing-fiesta-2024.md
          - es_ES/swing-a-esgaya-2024.md
          - es_ES/barcelona-shag-festival-2024.md
          - es_ES/the-jump-2024.md
          - es_ES/barcelona-lindy-exchange-2024.md
          - es_ES/swim-out-costa-brava-2024.md
          - es_ES/morella-swing-weekend-2024.md
          - es_ES/jazz-n-swing-gasteiz-festival-2024.md
          - es_ES/festival-swing-monachil-2024.md
          - es_ES/metropoli-fest-2024.md
          - es_ES/sevilla-swing-festival-2024.md
          - es_ES/move-your-bottom-2024.md
        - Archives:
          - es_ES/2024.md
      - Belgium:
        - Timeline: fr_BE/index.md
        - Events by City: fr_BE/by_city.md
        - Host Cities: fr_BE/host_cities.md
        - Collected Events:
          - fr_BE/boulevard-blues-2024.md
        - Archives:
          - fr_BE/2024.md
      - France:
        - Timeline: fr_FR/index.md
        - Events by City: fr_FR/by_city.md
        - Host Cities: fr_FR/host_cities.md
        - Collected Events:
          - fr_FR/tours-n-swing-2025.md
          - fr_FR/swingamann-2024.md
          - fr_FR/lyon-swing-festival-2024.md
          - fr_FR/rainy-blues-2024.md
          - fr_FR/toulouse-swing-exchange-2024.md
          - fr_FR/savoie-balboa-festival-2024.md
          - fr_FR/tours-n-balboa-2024.md
          - fr_FR/la-plagne-swing-2024.md
          - fr_FR/summer-camp-blues-week-2024.md
          - fr_FR/summer-camp-lindy-week-2024.md
          - fr_FR/anduze-jazz-dance-camp-2024.md
          - fr_FR/summer-camp-balboa-week-2024.md
        - Archives:
          - fr_FR/2025.md
          - fr_FR/2024.md
      - Italy:
        - Timeline: it_IT/index.md
        - Events by City: it_IT/by_city.md
        - Host Cities: it_IT/host_cities.md
        - Collected Events:
          - it_IT/sunny-slide-swing-fest-2025.md
          - it_IT/brescia-balboa-series-may-2025.md
          - it_IT/swing-train-festival-2025.md
          - it_IT/brescia-balboa-series-apr-2025.md
          - it_IT/roma-balboa-weekend-2025.md
          - it_IT/brescia-balboa-series-mar-2025.md
          - it_IT/swing-in-roma-2025.md
          - it_IT/brescia-balboa-series-feb-2025.md
          - it_IT/milan-balboa-weekend-2025.md
          - it_IT/tuscany-balboa-weekend-2025.md
          - it_IT/crazy-blues-2025.md
          - it_IT/keep-on-swingin-2025.md
          - it_IT/brescia-balboa-series-jan-2025.md
          - it_IT/brescia-balboa-series-nov-2024.md
          - it_IT/swing-n-milan-2024.md
          - it_IT/brescia-balboa-series-oct-2024.md
          - it_IT/swingala-2024.md
          - it_IT/sicily-swing-fest-2024.md
          - it_IT/balboario-2024.md
          - it_IT/policoro-in-swing-2024.md
          - it_IT/bal-n-lindy-vintage-festival-2024.md
          - it_IT/swing-in-the-amalfi-coast-2024.md
        - Archives:
          - it_IT/2025.md
          - it_IT/2024.md
      - Luxembourg:
        - Timeline: lb_LU/index.md
        - Events by City: lb_LU/by_city.md
        - Host Cities: lb_LU/host_cities.md
        - Collected Events:
          - lb_LU/swing-the-abbey-2024.md
        - Archives:
          - lb_LU/2024.md
      - Lithuania:
        - Timeline: lt_LT/index.md
        - Events by City: lt_LT/by_city.md
        - Host Cities: lt_LT/host_cities.md
        - Collected Events:
          - lt_LT/uptown-rhythm-2025.md
          - lt_LT/vilnius-shag-festival-2024.md
          - lt_LT/all-lithuanian-weekend-2024.md
          - lt_LT/bluesila-2024.md
          - lt_LT/what-a-jazz-summer-camp-2024.md
        - Archives:
          - lt_LT/2025.md
          - lt_LT/2024.md
      - Norway:
        - Timeline: nb_NO/index.md
        - Events by City: nb_NO/by_city.md
        - Host Cities: nb_NO/host_cities.md
        - Collected Events:
          - nb_NO/bal-heim-2025.md
          - nb_NO/scandinavian-shuffle-2025.md
          - nb_NO/swing-brother-swing-2024.md
          - nb_NO/oslo-balboa-weekend-2024.md
          - nb_NO/o-slow-2024.md
          - nb_NO/slow-balboa-boost-2024.md
          - nb_NO/boogie-feets-festival-2024.md
        - Archives:
          - nb_NO/2025.md
          - nb_NO/2024.md
      - Netherlands:
        - Timeline: nl_NL/index.md
        - Events by City: nl_NL/by_city.md
        - Host Cities: nl_NL/host_cities.md
        - Collected Events:
          - nl_NL/the-vintage-battle-of-the-bands-2024.md
          - nl_NL/swing-dom-2024.md
          - nl_NL/the-mess-around-2024.md
        - Archives:
          - nl_NL/2024.md
      - Poland:
        - Timeline: pl_PL/index.md
        - Events by City: pl_PL/by_city.md
        - Host Cities: pl_PL/host_cities.md
        - Collected Events:
          - pl_PL/lindy-szaus-birthday-jam-2025.md
          - pl_PL/dragon-swing-festival-2024.md
          - pl_PL/rock-the-balboa-2024.md
          - pl_PL/lindy-hop-non-stop-2024.md
          - pl_PL/lindy-szaus-birthday-jam-2024.md
        - Archives:
          - pl_PL/2025.md
          - pl_PL/2024.md
      - Russia:
        - Timeline: ru_RU/index.md
        - Events by City: ru_RU/by_city.md
        - Host Cities: ru_RU/host_cities.md
        - Collected Events:
          - ru_RU/moscow-comes-around-2024.md
        - Archives:
          - ru_RU/2024.md
      - Slovenia:
        - Timeline: sl_SI/index.md
        - Events by City: sl_SI/by_city.md
        - Host Cities: sl_SI/host_cities.md
        - Collected Events:
          - sl_SI/vintage-swing-festival-2024.md
          - sl_SI/haniBal-balboa-festival-2024.md
        - Archives:
          - sl_SI/2024.md
      - Sweden:
        - Timeline: sv_SE/index.md
        - Events by City: sv_SE/by_city.md
        - Host Cities: sv_SE/host_cities.md
        - Collected Events:
          - sv_SE/the-snowball-2024.md
          - sv_SE/gothenburg-queer-lindy-festival-2024.md
          - sv_SE/heedman-dance-camp-2024.md
          - sv_SE/herrang-dance-camp-2024.md
        - Archives:
          - sv_SE/2024.md
    - Oceania:
      - Australia:
        - Timeline: en_AU/index.md
        - Events by City: en_AU/by_city.md
        - Host Cities: en_AU/host_cities.md
        - Collected Events:
          - en_AU/hullabaloo-2025.md
          - en_AU/jurassic-bal-2025.md
          - en_AU/the-adelaide-lindy-exchange-2025.md
          - en_AU/remy-n-ramona-weekend-2024.md
          - en_AU/melbourne-lindy-exchange-2024.md
          - en_AU/lindy-rovale-2024.md
          - en_AU/brisbane-balboa-weekend-2024.md
          - en_AU/boogie-down-south-2024.md
          - en_AU/spring-mini-blues-weekend-2024.md
          - en_AU/sydney-lindy-exchange-2024.md
          - en_AU/gold-coast-lindy-fest-2024.md
          - en_AU/winter-swing-festival-2024.md
          - en_AU/brisbane-swing-thing-2024.md
          - en_AU/jurassic-bal-2024.md
        - Archives:
          - en_AU/2025.md
          - en_AU/2024.md
  - Orgs: https://swing.kids
  - Changelogs: https://github.com/swingdance/events/commits/main/
  - About:
    - references.md
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: submit.md
