INHERIT: '../base.yml'

docs_dir: '../../src/en'
site_dir: '../../build'

theme:
  name: material
  language: en

plugins:
  - search
  - tags:
      tags_file: tags.md
  - social:
      cards_layout_options:
        background_color: "#14151A"

site_description: 'A collection of swing dance events from around the world.'
nav:
  - Home:
    - Timeline: index.md
    - Tags: tags.md
    - Archives:
      - '2025': 2025.md
      - '2024': 2024.md
  - Regions:
    - All: regions.md
    - America:
      - Canada:
        - Timeline: ca/index.md
        - Events by City: ca/by_city.md
        - Host Cities: ca/host_cities.md
        - Collected Events:
          - ca/capital-city-stomp-2024.md
          - ca/cats-corner-exchange-2024.md
          - ca/vancouver-balboa-mini-fest-2024.md
          - ca/lindy-harvest-2024.md
          - ca/rhythm-city-mess-around-2024.md
          - ca/stardust-festival-2024.md
        - Archives:
          - ca/2024.md
      - Chile:
        - Timeline: cl/index.md
        - Events by City: cl/by_city.md
        - Host Cities: cl/host_cities.md
        - Collected Events:
          - cl/lindy-poh-2024.md
        - Archives:
          - cl/2024.md
      - Mexico:
        - Timeline: mx/index.md
        - Events by City: mx/by_city.md
        - Host Cities: mx/host_cities.md
        - Collected Events:
          - mx/guadalajara-lindy-exchange-2024.md
          - mx/lindy-n-balboa-maya-fest-2024.md
          - mx/mexico-lindy-querido-2024.md
        - Archives:
          - mx/2024.md
      - United States:
        - Timeline: us/index.md
        - Events by City: us/by_city.md
        - Host Cities: us/host_cities.md
        - Collected Events:
          - us/hot-rhythm-holiday-2025.md
          - us/california-balboa-classic-2025.md
          - us/stormy-weather-jazz-festival-2024.md
          - us/hot-jazz-jamboree-2024.md
          - us/stompology-2024.md
          - us/breaking-bal-swing-n-blues-weekend-2024.md
          - us/emerald-city-blues-festival-2024.md
          - us/blues-muse-2024.md
          - us/stl-getdown-2024.md
          - us/great-lakes-balboa-escape-2024.md
          - us/new-york-lindy-exchange-2024.md
          - us/lindy-on-the-rocks-2024.md
          - us/hot-night-fusion-weekend-2024.md
          - us/cowtown-jamborama-2024.md
          - us/camp-hollywood-2024.md
          - us/the-uptown-swingout-2024.md
          - us/swing-out-new-hampshire-2024.md
          - us/summer-swing-fest-2024.md
          - us/rittenhopalooza-2024.md
          - us/cincy-hop-2024.md
          - us/flying-home-2024.md
          - us/bal-week-2024.md
          - us/california-balboa-classic-2024.md
        - Archives:
          - us/2025.md
          - us/2024.md
    - Asia:
      - Armenia:
        - Timeline: am/index.md
        - Events by City: am/by_city.md
        - Host Cities: am/host_cities.md
        - Collected Events:
          - am/swing-road-armenia-2024.md
        - Archives:
          - am/2024.md
      - China:
        - Timeline: cn/index.md
        - Events by City: cn/by_city.md
        - Host Cities: cn/host_cities.md
        - Collected Events:
          - cn/shanghai-lindy-festival-2024.md
          - cn/swingtime-ball-2024.md
          - cn/shanghai-balboa-weekend-2024.md
          - cn/swing-paramount-2024.md
          - cn/womens-jazzination-2024.md
          - cn/claudia-n-coline-workshop-2024.md
          - cn/beijing-blues-bush-2024.md
          - cn/westlake-swing-carnival-2024.md
          - cn/blues-heat-2024.md
          - cn/swing-feast-2024.md
          - cn/balboa-greater-bay-workshop-2024.md
          - cn/hangzhou-swing-10th-anniversary-2024.md
          - cn/blues-workshop-with-taehyeon-2024.md
          - cn/jazz-do-it-2024.md
          - cn/funs-swing-exchange-2024.md
          - cn/bal-in-beijing-2024.md
          - cn/balboa-festival-2024.md
          - cn/jump-for-joy-2024.md
          - cn/dragon-boat-swing-camp-2024.md
          - cn/dali-lalla-n-sunny-workshop-2024.md
          - cn/vasu-n-nan-balboa-workshop-2024.md
          - cn/nanjing-lindy-festival-2024.md
          - cn/xiamen-kiki-house-african-dance-workshop-2024.md
          - cn/awozi-n-lis-fuzhou-workshop-2024.md
          - cn/shanghai-blues-camp-2024.md
          - cn/beijing-balboa-fever-2024.md
          - cn/jumping-swing-2024.md
          - cn/balboa-spring-camp-2024.md
          - cn/bouncy-chengdu-2024.md
          - cn/beijing-sharon-davis-workshop-2024.md
          - cn/lindy-hotpot-2024.md
          - cn/xiamen-awozi-n-lis-workshop-2024.md
          - cn/groove-the-blusy-bay-2024.md
          - cn/all-balboa-exchange-2024.md
          - cn/xiamen-jiaming-n-wanyuan-workshop-2024.md
          - cn/beijing-balboa-travel-2024.md
        - Archives:
          - cn/2024.md
      - Hong Kong:
        - Timeline: hk/index.md
        - Events by City: hk/by_city.md
        - Host Cities: hk/host_cities.md
        - Collected Events:
          - hk/harbourside-swing-fest-2025.md
          - hk/vasu-n-xinru-balboa-weekend-2024.md
          - hk/harbourside-swing-fest-2024.md
        - Archives:
          - hk/2025.md
          - hk/2024.md
      - Indonesia:
        - Timeline: id/index.md
        - Events by City: id/by_city.md
        - Host Cities: id/host_cities.md
        - Collected Events:
          - id/bali-lindy-exchange-2024.md
        - Archives:
          - id/2024.md
      - Japan:
        - Timeline: jp/index.md
        - Events by City: jp/by_city.md
        - Host Cities: jp/host_cities.md
        - Collected Events:
          - jp/tokyo-balboa-weekend-2024.md
          - jp/swing-owl-halloween-2024.md
          - jp/osaka-lindy-exchange-2024.md
          - jp/swing-owl-08-2024.md
          - jp/swing-jack-2024.md
          - jp/yokohama-cross-street-hop-07-2024.md
          - jp/bal-in-tokyo-2024.md
          - jp/chocolate-shake-07-2024.md
          - jp/swingin-n-hoppin-sapporp-2024.md
          - jp/yokohama-cross-street-hop-06-2024.md
          - jp/tomodachi-swing-2024.md
          - jp/swing-owl-06-2024.md
          - jp/chocolate-shake-06-2024.md
          - jp/balboa-lab-tea-party-2024.md
          - jp/chill-balboa-social-2024.md
        - Archives:
          - jp/2024.md
      - South Korea:
        - Timeline: kr/index.md
        - Events by City: kr/by_city.md
        - Host Cities: kr/host_cities.md
        - Collected Events:
          - kr/savoy-cup-asia-2024.md
          - kr/korean-balboa-weekend-2024.md
          - kr/seoul-lindy-fest-2024.md
          - kr/bal-hop-2024.md
          - kr/champions-cup-korea-2024.md
          - kr/rhythm-korea-2024.md
        - Archives:
          - kr/2024.md
      - Thailand:
        - Timeline: th/index.md
        - Events by City: th/by_city.md
        - Host Cities: th/host_cities.md
        - Collected Events:
          - th/diga-diga-doo-2024.md
          - th/swing-era-2024.md
          - th/breezy-balboa-2024.md
        - Archives:
          - th/2024.md
      - Turkey:
        - Timeline: tr/index.md
        - Events by City: tr/by_city.md
        - Host Cities: tr/host_cities.md
        - Collected Events:
          - tr/jumpin-at-istanbul-2025.md
        - Archives:
          - tr/2025.md
      - Taiwan:
        - Timeline: tw/index.md
        - Events by City: tw/by_city.md
        - Host Cities: tw/host_cities.md
        - Collected Events:
          - tw/what-the-pa-2024.md
        - Archives:
          - tw/2024.md
    - Europe:
      - Belgium:
        - Timeline: be/index.md
        - Events by City: be/by_city.md
        - Host Cities: be/host_cities.md
        - Collected Events:
          - be/boulevard-blues-2024.md
        - Archives:
          - be/2024.md
      - Switzerland:
        - Timeline: ch/index.md
        - Events by City: ch/by_city.md
        - Host Cities: ch/host_cities.md
        - Collected Events:
          - ch/bal-inspiration-2025.md
          - ch/stir-it-2024.md
          - ch/rocky-balberna-2024.md
          - ch/shake-that-lake-2024.md
          - ch/shag-delight-2024.md
        - Archives:
          - ch/2025.md
          - ch/2024.md
      - Czechia:
        - Timeline: cz/index.md
        - Events by City: cz/by_city.md
        - Host Cities: cz/host_cities.md
        - Collected Events:
          - cz/slow-bal-love-2024.md
          - cz/bal-love-2024.md
        - Archives:
          - cz/2024.md
      - Germany:
        - Timeline: de/index.md
        - Events by City: de/by_city.md
        - Host Cities: de/host_cities.md
        - Collected Events:
          - de/swingcake-tubingen-2025.md
          - de/b-t-switch-2025.md
          - de/berlin-balboa-weekend-2025.md
          - de/rock-that-swing-festival-2025.md
          - de/swing-it-berlin-2025.md
          - de/slow-balboa-weekend-munich-2025.md
          - de/xma-swing-2024.md
          - de/autumn-leaves-the-pott-2024.md
          - de/sandy-lewis-workshop-2024.md
          - de/hully-hop-swing-farm-2024.md
          - de/balboa-date-stuttgart-2024.md
          - de/augsburg-boogie-festival-2024.md
          - de/swinging-marzipan-lubeck-2024.md
          - de/swingin-charlie-2024.md
          - de/broadway-swing-2024.md
          - de/mainhatten-shuffle-2024.md
          - de/swing-man-tau-2024.md
          - de/munich-balboa-n-shag-weekend-2024.md
          - de/da-solo-jazz-festival-2024.md
          - de/are-you-syncopated-2024.md
          - de/swingomania-2024.md
          - de/lindy-cake-2024.md
          - de/blues-dance-retreat-2024.md
          - de/flying-feet-stuttgart-2024.md
          - de/boost-lindy-hop-workshop-2024.md
          - de/hully-blues-2024.md
          - de/augsburg-balboa-festival-2024.md
          - de/swing-it-konstanz-2024.md
          - de/hannover-swing-exchange-2024.md
          - de/lindy-hop-trainingslager-2024.md
          - de/shag-ahoi-2024.md
          - de/harvest-moon-swing-dance-camp-2024.md
          - de/velo-swing-festival-2024.md
        - Archives:
          - de/2025.md
          - de/2024.md
      - Denmark:
        - Timeline: dk/index.md
        - Events by City: dk/by_city.md
        - Host Cities: dk/host_cities.md
        - Collected Events:
          - dk/copenhagen-balboa-weekend-2024.md
          - dk/why-not-aarhus-lindy-exchange-2024.md
        - Archives:
          - dk/2024.md
      - Spain:
        - Timeline: es/index.md
        - Events by City: es/by_city.md
        - Host Cities: es/host_cities.md
        - Collected Events:
          - es/barcelona-balboa-festival-2024.md
          - es/espanish-blues-festival-2024.md
          - es/mojo-swing-tropical-fest-2024.md
          - es/swing-fest-malaga-2024.md
          - es/swing-ciudad-real-2024.md
          - es/donosti-belle-swing-festival-2024.md
          - es/cadiz-swing-festival-2024.md
          - es/stomp-your-feet-2024.md
          - es/calpe-swing-fiesta-2024.md
          - es/swing-a-esgaya-2024.md
          - es/barcelona-shag-festival-2024.md
          - es/the-jump-2024.md
          - es/barcelona-lindy-exchange-2024.md
          - es/swim-out-costa-brava-2024.md
          - es/morella-swing-weekend-2024.md
          - es/jazz-n-swing-gasteiz-festival-2024.md
          - es/festival-swing-monachil-2024.md
          - es/metropoli-fest-2024.md
          - es/sevilla-swing-festival-2024.md
          - es/move-your-bottom-2024.md
        - Archives:
          - es/2024.md
      - France:
        - Timeline: fr/index.md
        - Events by City: fr/by_city.md
        - Host Cities: fr/host_cities.md
        - Collected Events:
          - fr/tours-n-swing-2025.md
          - fr/the-battle-2025.md
          - fr/european-balboa-festival-2024.md
          - fr/swingamann-2024.md
          - fr/lyon-swing-festival-2024.md
          - fr/rainy-blues-2024.md
          - fr/toulouse-swing-exchange-2024.md
          - fr/savoie-balboa-festival-2024.md
          - fr/tours-n-balboa-2024.md
          - fr/la-plagne-swing-2024.md
          - fr/summer-camp-blues-week-2024.md
          - fr/summer-camp-lindy-week-2024.md
          - fr/anduze-jazz-dance-camp-2024.md
          - fr/summer-camp-balboa-week-2024.md
        - Archives:
          - fr/2025.md
          - fr/2024.md
      - Greece:
        - Timeline: gr/index.md
        - Events by City: gr/by_city.md
        - Host Cities: gr/host_cities.md
        - Collected Events:
          - gr/wild-west-festival-2024.md
          - gr/crete-on-the-beat-2024.md
        - Archives:
          - gr/2024.md
      - Italy:
        - Timeline: it/index.md
        - Events by City: it/by_city.md
        - Host Cities: it/host_cities.md
        - Collected Events:
          - it/sunny-slide-swing-fest-2025.md
          - it/brescia-balboa-series-may-2025.md
          - it/swing-train-festival-2025.md
          - it/brescia-balboa-series-apr-2025.md
          - it/roma-balboa-weekend-2025.md
          - it/brescia-balboa-series-mar-2025.md
          - it/swing-in-roma-2025.md
          - it/brescia-balboa-series-feb-2025.md
          - it/milan-balboa-weekend-2025.md
          - it/tuscany-balboa-weekend-2025.md
          - it/crazy-blues-2025.md
          - it/keep-on-swingin-2025.md
          - it/brescia-balboa-series-jan-2025.md
          - it/brescia-balboa-series-nov-2024.md
          - it/swing-n-milan-2024.md
          - it/brescia-balboa-series-oct-2024.md
          - it/swingala-2024.md
          - it/sicily-swing-fest-2024.md
          - it/balboario-2024.md
          - it/policoro-in-swing-2024.md
          - it/bal-n-lindy-vintage-festival-2024.md
          - it/swing-in-the-amalfi-coast-2024.md
        - Archives:
          - it/2025.md
          - it/2024.md
      - Lithuania:
        - Timeline: lt/index.md
        - Events by City: lt/by_city.md
        - Host Cities: lt/host_cities.md
        - Collected Events:
          - lt/uptown-rhythm-2025.md
          - lt/vilnius-shag-festival-2024.md
          - lt/all-lithuanian-weekend-2024.md
          - lt/bluesila-2024.md
          - lt/what-a-jazz-summer-camp-2024.md
        - Archives:
          - lt/2025.md
          - lt/2024.md
      - Luxembourg:
        - Timeline: lu/index.md
        - Events by City: lu/by_city.md
        - Host Cities: lu/host_cities.md
        - Collected Events:
          - lu/swing-the-abbey-2024.md
        - Archives:
          - lu/2024.md
      - Netherlands:
        - Timeline: nl/index.md
        - Events by City: nl/by_city.md
        - Host Cities: nl/host_cities.md
        - Collected Events:
          - nl/the-vintage-battle-of-the-bands-2024.md
          - nl/swing-dom-2024.md
          - nl/the-mess-around-2024.md
        - Archives:
          - nl/2024.md
      - Norway:
        - Timeline: no/index.md
        - Events by City: no/by_city.md
        - Host Cities: no/host_cities.md
        - Collected Events:
          - no/bal-heim-2025.md
          - no/scandinavian-shuffle-2025.md
          - no/swing-brother-swing-2024.md
          - no/oslo-balboa-weekend-2024.md
          - no/o-slow-2024.md
          - no/slow-balboa-boost-2024.md
          - no/boogie-feets-festival-2024.md
        - Archives:
          - no/2025.md
          - no/2024.md
      - Poland:
        - Timeline: pl/index.md
        - Events by City: pl/by_city.md
        - Host Cities: pl/host_cities.md
        - Collected Events:
          - pl/lindy-szaus-birthday-jam-2025.md
          - pl/dragon-swing-festival-2024.md
          - pl/rock-the-balboa-2024.md
          - pl/lindy-hop-non-stop-2024.md
          - pl/lindy-szaus-birthday-jam-2024.md
        - Archives:
          - pl/2025.md
          - pl/2024.md
      - Russia:
        - Timeline: ru/index.md
        - Events by City: ru/by_city.md
        - Host Cities: ru/host_cities.md
        - Collected Events:
          - ru/moscow-comes-around-2024.md
        - Archives:
          - ru/2024.md
      - Sweden:
        - Timeline: se/index.md
        - Events by City: se/by_city.md
        - Host Cities: se/host_cities.md
        - Collected Events:
          - se/the-snowball-2024.md
          - se/gothenburg-queer-lindy-festival-2024.md
          - se/heedman-dance-camp-2024.md
          - se/herrang-dance-camp-2024.md
        - Archives:
          - se/2024.md
      - Slovenia:
        - Timeline: si/index.md
        - Events by City: si/by_city.md
        - Host Cities: si/host_cities.md
        - Collected Events:
          - si/vintage-swing-festival-2024.md
          - si/haniBal-balboa-festival-2024.md
        - Archives:
          - si/2024.md
      - United Kingdom:
        - Timeline: uk/index.md
        - Events by City: uk/by_city.md
        - Host Cities: uk/host_cities.md
        - Collected Events:
          - uk/lindy-in-the-sky-with-diamonds-2025.md
          - uk/the-savoy-jazz-jam-2024.md
          - uk/cambridge-lindy-exchange-2024.md
          - uk/atomic-cocktail-2024.md
          - uk/swing-city-brighton-weekend-2024.md
          - uk/northern-slow-bal-celebration-2024.md
          - uk/mersey-swing-smackdown-2024.md
          - uk/fast-feet-festival-2024.md
          - uk/belta-blues-2024.md
          - uk/edinburgh-lindy-exchange-2024.md
          - uk/nighthawks-summer-weekender-2024.md
          - uk/bal-break-at-the-livermead-cliff-2024.md
          - uk/hep-to-the-hive-2024.md
        - Archives:
          - uk/2025.md
          - uk/2024.md
    - Oceania:
      - Australia:
        - Timeline: au/index.md
        - Events by City: au/by_city.md
        - Host Cities: au/host_cities.md
        - Collected Events:
          - au/hullabaloo-2025.md
          - au/jurassic-bal-2025.md
          - au/the-adelaide-lindy-exchange-2025.md
          - au/remy-n-ramona-weekend-2024.md
          - au/melbourne-lindy-exchange-2024.md
          - au/lindy-rovale-2024.md
          - au/brisbane-balboa-weekend-2024.md
          - au/boogie-down-south-2024.md
          - au/spring-mini-blues-weekend-2024.md
          - au/sydney-lindy-exchange-2024.md
          - au/gold-coast-lindy-fest-2024.md
          - au/winter-swing-festival-2024.md
          - au/brisbane-swing-thing-2024.md
          - au/jurassic-bal-2024.md
        - Archives:
          - au/2025.md
          - au/2024.md
  - Orgs: https://swing.kids
  - Changelogs: https://github.com/swingdance/events/commits/main/
  - About:
    - references.md
    - support.md
    - Privacy & Terms:
      - privacy.md
      - terms.md
  - + Submit Org/Event: submit.md
