name: Deploy Static Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-n-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish
        uses: Kjuly/mkdocs-page-publisher@main
        with:
          config-files: |-
            config/en/mkdocs.yml
            config/zh-Hans/mkdocs.yml
