name: Deploy Static Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build-n-deploy:
    uses: Kjuly/mkdocs-page-publisher@main
    with:
      config-files: |-
        config/en/mkdocs.yml
        config/zh-Hans/mkdocs.yml
